name: Code Check

on:
  pull_request:
    branches:
      - develop
      - staging

jobs:
  checkCode:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: use Node.js 21.x
        uses: actions/setup-node@v1
        with: 
          node-version: 21.x
      

